// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: clgAdministration.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdministrationClient is the client API for Administration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdministrationClient interface {
	CreateCourse(ctx context.Context, in *CourseInfo, opts ...grpc.CallOption) (*Res, error)
}

type administrationClient struct {
	cc grpc.ClientConnInterface
}

func NewAdministrationClient(cc grpc.ClientConnInterface) AdministrationClient {
	return &administrationClient{cc}
}

func (c *administrationClient) CreateCourse(ctx context.Context, in *CourseInfo, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/GoPractise.Administration/CreateCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdministrationServer is the server API for Administration service.
// All implementations must embed UnimplementedAdministrationServer
// for forward compatibility
type AdministrationServer interface {
	CreateCourse(context.Context, *CourseInfo) (*Res, error)
	mustEmbedUnimplementedAdministrationServer()
}

// UnimplementedAdministrationServer must be embedded to have forward compatible implementations.
type UnimplementedAdministrationServer struct {
}

func (UnimplementedAdministrationServer) CreateCourse(context.Context, *CourseInfo) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedAdministrationServer) mustEmbedUnimplementedAdministrationServer() {}

// UnsafeAdministrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdministrationServer will
// result in compilation errors.
type UnsafeAdministrationServer interface {
	mustEmbedUnimplementedAdministrationServer()
}

func RegisterAdministrationServer(s grpc.ServiceRegistrar, srv AdministrationServer) {
	s.RegisterService(&Administration_ServiceDesc, srv)
}

func _Administration_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdministrationServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoPractise.Administration/CreateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdministrationServer).CreateCourse(ctx, req.(*CourseInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Administration_ServiceDesc is the grpc.ServiceDesc for Administration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Administration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GoPractise.Administration",
	HandlerType: (*AdministrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCourse",
			Handler:    _Administration_CreateCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clgAdministration.proto",
}
